---
- name: Up & Run the Clickhouse Server in Docker
  hosts: 127.0.0.1
  gather_facts: false

  vars:
    clickhouse_container: ch

  vars_prompt:

    - name: ch_host
      prompt: Managed ClickHouse host?
      private: no

    - name: ch_user
      prompt: Managed ClickHouse user?
      private: no

    - name: ch_database 
      prompt: Managed ClickHouse database?
      private: no

  pre_tasks:

    - name: Gather container info
      docker_container_info:
        name: '{{ clickhouse_container }}'
      register: result

    - fail:
        msg: Container with name '{{ clickhouse_container }}' already exists
      when: result.exists
    
    - name: Up & Run container with Clickhouse
      docker_container:
        image: yandex/clickhouse-server:20
        name: '{{ clickhouse_container }}'
        ports: 127.0.0.1:9000:9000
        env:
          DEBIAN_FRONTEND: noninteractive

    - name: Add host to inventory
      add_host:
        hostname: '{{ clickhouse_container }}'
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3

    - name: Install python3 & lxml
      raw: >
        apt update &&
        apt install -y python3 python3-lxml
      delegate_to: '{{ clickhouse_container }}'

  tasks:

    - name: Grant default user ability to create new users
      xml:
        path: /etc/clickhouse-server/users.xml
        xpath: /yandex/users/default/access_management
        value: '1'
      delegate_to: '{{ clickhouse_container }}'

    - name: Install Yandex.Cloud cert
      shell: |
        mkdir -p ~/.clickhouse-client /usr/local/share/ca-certificates/Yandex
        wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt 
        wget "https://storage.yandexcloud.net/mdb/clickhouse-client.conf.example" -O ~/.clickhouse-client/config.xml
      delegate_to: '{{ clickhouse_container }}'

    - name: Create connect script to Managed ClickHouse
      copy:
        dest: "/usr/bin/connect.sh"
        mode: 0755
        content: |
          #!/usr/bin/env sh
          clickhouse-client \
              --host {{ ch_host }} \
              --secure \
              --user {{ ch_user }} \
              --database {{ ch_database }} \
              --port 9440 \
              --ask-password
      delegate_to: '{{ clickhouse_container }}'

  post_tasks:
    
    - name: Remove python3 & lxml
      raw: apt remove -y python3 python3-lxml
      delegate_to: '{{ clickhouse_container }}'
...
